spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hubzu?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  liquibase:
    url: jdbc:mysql://localhost:3306/hubzu?useUnicode=true&characterEncoding=utf8
    user: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      hibernate:
        SQL: info
        type:
          descriptor:
            sql: info
hubzu:
  image:
    root:
      folder: /home/ferdoganf/hubzutmp
  url:
    base: http://localhost:3000
  mail:
    admin: ferdoganf@gmail.com
    from: ferdoganf@gmail.com
    bcc: ferdoganf@gmail.com
    contactus:
      to: ferdoganf@gmail.com