package com.hubzu.api.util;

public class ErrorCodes {
    public static final String VALIDATION_NOT_VALID = "VALIDATION_NOT_VALID";
    public static final String VALIDATION_EMPTY = "VALIDATION_EMPTY";


    public static final String ERROR_BUYER_NOT_FOUND = "ERROR_BUYER_NOT_FOUND";
    public static final String ERROR_RESIDENTIAL_REAL_ESTATE_NOT_FOUND = "ERROR_RESIDENTIAL_REAL_ESTATE_NOT_FOUND";
    public static final String ERROR_COMMERCIAL_REAL_ESTATE_NOT_FOUND = "ERROR_COMMERCIAL_REAL_ESTATE_NOT_FOUND";
    public static final String ERROR_LAND_REAL_ESTATE_NOT_FOUND = "ERROR_LAND_REAL_ESTATE_NOT_FOUND";
    public static final String ERROR_REAL_ESTATE_PARAM_NOT_FOUND = "ERROR_REAL_ESTATE_PARAM_NOT_FOUND";
    public static final String ERROR_REAL_ESTATE_ALREADY_EXISTS_BY_CODE = "ERROR_REAL_ESTATE_ALREADY_EXISTS_BY_CODE";
    public static final String ERROR_REAL_ESTATE_NOT_FOUND = "ERROR_REAL_ESTATE_NOT_FOUND";
    public static final String ERROR_REAL_ESTATE_STATUS_NOT_FOUND = "ERROR_REAL_ESTATE_STATUS_NOT_FOUND";
    public static final String ERROR_CITY_NOT_FOUND = "ERROR_CITY_NOT_FOUND";
    public static final String ERROR_DISTRICT_NOT_FOUND = "ERROR_DISTRICT_NOT_FOUND";
    public static final String ERROR_NEIGHBORHOOD_NOT_FOUND = "ERROR_NEIGHBORHOOD_NOT_FOUND";
    public static final String ERROR_BANK_NOT_FOUND = "ERROR_BANK_NOT_FOUND";
    public static final String ERROR_SMS_NOT_FOUND = "ERROR_SMS_NOT_FOUND";
    public static final String ERROR_ACTIVE_REAL_ESTATE_CANNOT_BE_UPDATED = "ERROR_ACTIVE_REAL_ESTATE_CANNOT_BE_UPDATED";
    public static final String ERROR_CLOSED_REAL_ESTATE_CANNOT_BE_UPDATED = "ERROR_CLOSED_REAL_ESTATE_CANNOT_BE_UPDATED";
    public static final String ERROR_USER_TYPE_NOT_FOUND = "ERROR_USER_TYPE_NOT_FOUND";
    public static final String ERROR_USER_STATUS_NOT_FOUND = "ERROR_USER_STATUS_NOT_FOUND";
    public static final String ERROR_USER_NOT_FOUND = "ERROR_USER_NOT_FOUND";
    public static final String ERROR_FILE_NAME_IS_NULL = "ERROR_FILE_NAME_IS_NULL";
    public static final String ERROR_FILE_NAME_IS_NOT_VALID = "ERROR_FILE_NAME_IS_NOT_VALID";
    public static final String ERROR_FILE_TYPE_IS_NOT_VALID = "ERROR_FILE_TYPE_IS_NOT_VALID";
    public static final String ERROR_FILE_CANNOT_BE_WRITE = "ERROR_FILE_CANNOT_BE_WRITE";
    public static final String ERROR_PHOTO_NOT_FOUND = "ERROR_PHOTO_NOT_FOUND";
    public static final String ERROR_FILE_CANNOT_BE_DELETED = "ERROR_FILE_CANNOT_BE_DELETED";
    public static final String ERROR_REAL_ESTATE_TYPE_INVALID = "ERROR_REAL_ESTATE_TYPE_INVALID";
    public static final String ERROR_BUYER_ALREADY_EXISTS = "ERROR_BUYER_ALREADY_EXISTS";
    public static final String ERROR_BUYER_ALREADY_EXISTS_WITH_EMAIL_ADDRESS = "ERROR_BUYER_ALREADY_EXISTS_WITH_EMAIL_ADDRESS";
    public static final String ERROR_BID_AMOUNT_SUFFICIENT = "ERROR_BID_AMOUNT_SUFFICIENT";
    public static final String ERROR_USER_STATUS_IS_NOT_APPROPRIATE_FOR_BID = "ERROR_USER_STATUS_IS_NOT_APPROPRIATE_FOR_BID";
    public static final String ERROR_BID_AMOUNT_STEP_INVALID = "ERROR_BID_AMOUNT_STEP_INVALID";
    public static final String ERROR_REAL_ESTATE_NEW_STATUS_IS_NOT_VALID = "ERROR_REAL_ESTATE_NEW_STATUS_IS_NOT_VALID";
    public static final String ERROR_USER_HAS_NO_WARRANT_FOR_REAL_ESTATE = "ERROR_USER_HAS_NO_WARRANT_FOR_REAL_ESTATE";
    public static final String ERROR_INVALID_PASSWORD = "ERROR_INVALID_PASSWORD";
    public static final String ERROR_AUCTION_END_DATE_NOT_APPROPRIATE_FOR_BID = "ERROR_AUCTION_END_DATE_NOT_APPROPRIATE_FOR_BID";
    public static final String ERROR_REAL_ESTATE_STATUS_NOT_VALID_FOR_COMPLETE = "ERROR_REAL_ESTATE_STATUS_NOT_VALID_FOR_COMPLETE";
    public static final String ERROR_AUCTION_END_DATE_NOT_VALID_FOR_COMPLETE = "ERROR_AUCTION_END_DATE_NOT_VALID_FOR_COMPLETE";
    public static final String ERROR_BID_AMOUNT_SUFFICIENT_BIG = "ERROR_BID_AMOUNT_SUFFICIENT_BIG";
    public static final String ERROR_BID_AMOUNT_SUFFICIENT_EQUAL = "ERROR_BID_AMOUNT_SUFFICIENT_EQUAL";
    public static final String ERROR_VISITOR_NOT_FOUND = "ERROR_VISITOR_NOT_FOUND";
    public static final String ERROR_VISITOR_ALREADY_EXISTS = "ERROR_VISITOR_ALREADY_EXISTS";
    public static final String ERROR_RECAPTCHA_TOKEN_NOT_VALID = "ERROR_RECAPTCHA_TOKEN_NOT_VALID";
    public static final String ERROR_BANK_ALREADY_EXISTS = "ERROR_BANK_ALREADY_EXISTS";
    public static final String ERROR_BUYER_HAS_ALREADY_AUTO_BID_FOR_THIS_REALESTATE = "ERROR_BUYER_HAS_ALREADY_AUTO_BID_FOR_THIS_REALESTATE";
    public static final String ERROR_AUTO_BID_NOT_FOUND = "ERROR_AUTO_BID_NOT_FOUND";
    public static final String ERROR_REAL_ESTATE_STATUS_IS_NOT_APPROPRIATE_FOR_BID = "ERROR_REAL_ESTATE_STATUS_IS_NOT_APPROPRIATE_FOR_BID";
    public static final String ERROR_REAL_ESTATE_STATUS_NOT_VALID_FOR_DELETE = "ERROR_REAL_ESTATE_STATUS_NOT_VALID_FOR_DELETE";
    public static final String ERROR_REAL_ESTATE_TYPE_NOT_FOUND = "ERROR_REAL_ESTATE_TYPE_NOT_FOUND";
    public static final String ERROR_REAL_ESTATE_SUB_TYPE_ALREADY_EXISTS = "ERROR_REAL_ESTATE_SUB_TYPE_ALREADY_EXISTS";
    public static final String ERROR_REAL_ESTATE_SUB_TYPE_IN_USE = "ERROR_REAL_ESTATE_SUB_TYPE_IN_USE";
    public static final String ERROR_ENTITY_NOT_FOUND = "ERROR_ENTITY_NOT_FOUND";
}
